# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseUser',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoneJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('expreward', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.DataBaseUser')),
                ('cash', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='donejobs',
            name='jobname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Jobs'),
        ),
        migrations.AddField(
            model_name='donejobs',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
    ]
