# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='level_requirement',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
