# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_jobs_levelrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='tasks',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
